name: Build GJS on Windows

on: [push]

jobs:
  Build-Mozjs:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup MozillaBuild
      shell: pwsh
      run: ./mozilla.bat
    - name: Build Mozjs
      shell: C:\mozilla-build\start-shell.bat ls && pwd && bash /d/a/gjs-on-windows/gjs-on-windows/mozjs.sh && echo '{0}'
      run: ./noop.sh